general.import = ["~/.config/alacritty/dracula.toml", "~/.config/alacritty/font.toml", "~/.config/alacritty/scrolling.toml"]

[window.padding]
x = 10
y = 5

[[keyboard.bindings]]
action = "ScrollPageUp"
key    = "PageUp"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key    = "PageDown"
mods   = "Shift"

[cursor]
style = "beam"
vi_mode_style = "beam"

[scrolling]
history = 10000
multiplier = 3
